In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
labels = ['a', 'b', 'c']

In [4]:
minha_lista = [10, 20, 30]

In [5]:
arr = np.array([[10, 20, 30]])

In [6]:
d = {'a': 10, 'b': 20, 'c': 30}

In [7]:
pd.Series (data=minha_lista, index=labels) #cria uma serie

a    10
b    20
c    30
dtype: int64

In [8]:
series = pd.Series (data=minha_lista, index=labels) # associa a uma variavel, fornecendo assim uma chamada mais simples

In [9]:
series['b'] #puxa somente do b.

np.int64(20)

In [10]:
pd.Series (labels, minha_lista) #pode ser qualquer tipo, string, numero...

10    a
20    b
30    c
dtype: object

In [11]:
pd.Series(minha_lista, labels)

a    10
b    20
c    30
dtype: int64

In [12]:
pd.Series(arr[0], labels) #aqui alterei o código da aula, por algum motivo (talvez versionamento do Colab que estou usando) ele nao aceita pd.Series(arr, labels).

a    10
b    20
c    30
dtype: int64

In [13]:
ser1 = pd.Series([1, 2, 3, 4], index=['EUA', 'Alemanha', 'URSS', 'Japan'])

In [14]:
ser1

EUA         1
Alemanha    2
URSS        3
Japan       4
dtype: int64

In [15]:
ser2 = pd.Series([1, 2, 3, 4], index=['EUA', 'Alemanha', 'Itália', 'Japan'])

In [16]:
ser2

EUA         1
Alemanha    2
Itália      3
Japan       4
dtype: int64

In [17]:
ser1 + ser2

Alemanha    4.0
EUA         2.0
Itália      NaN
Japan       8.0
URSS        NaN
dtype: float64

Aqui podem ser efetuadas operações matemáticas.

Aqui começa Cração e Fatiamento

In [18]:
np.random.seed(101) #gera os aleatórios

In [19]:
df = pd.DataFrame(np.random.randn(5, 4), index='A B C D E'.split(), columns='W X Y Z'.split()) #dados em 5x4

In [20]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [21]:
df['W'] #seleciona a coluna W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [22]:
type(df['W'])

pandas.core.series.Series

In [23]:
type(df)

pandas.core.frame.DataFrame

In [24]:
#acima mostra que é uma series ou um data frame

In [25]:
print('O código está sendo executado no ambiente do Google Colab.')

O código está sendo executado no ambiente do Google Colab.

In [26]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

Até pode fazer com o .W, mas não é recomendado

In [27]:
#df['new'] #nao funciona

In [28]:
df['new'] = df['W'] + df['X'] #cria nova colna somando W e X

In [29]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [30]:
df.drop('new', axis=1) #remove a coluna apenas na visulaização, nao altera a original

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [32]:
df.drop ('new', axis=1, inplace=True) #Aqui remove de verdade

In [33]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [34]:
df.loc['A', 'W'] #loc de localizaçao

np.float64(2.706849839399938)

In [35]:
df.loc[['A', 'B'], ['X', 'Y', 'Z']] #Pode passar uma lista também...

          X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965

In [36]:
df.iloc[1:4, 2:] #Pelos indices, assim como Numpy

          Y         Z
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057

In [37]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [38]:
df > 0 #verificar se é maior que zero, valores dentro. Aqui começa as seleções condicionais

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [39]:
bol = df > 0

In [40]:
df [bol]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [41]:
df[df['W']>0] #onde W maior que 0

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
df[df['W'] > 0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [43]:
bol = df['W'] > 0
df2 = df[bol]
df2['Y'] #equivalente

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [44]:
df[(df['W']>0) | (df['Y']>1)] #linhas de w maior que 0 e de y maior que 1

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [45]:
df.reset_index(inplace=True) #indice original no dataframe

In [46]:
df

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [47]:
col = 'RS RJ SP AM SC'.split() #lista abreviacao estados

In [48]:
col

['RS', 'RJ', 'SP', 'AM', 'SC']

In [49]:
df['Estado'] = col

In [50]:
df

  index         W         X         Y         Z Estado
0     A  2.706850  0.628133  0.907969  0.503826     RS
1     B  0.651118 -0.319318 -0.848077  0.605965     RJ
2     C -2.018168  0.740122  0.528813 -0.589001     SP
3     D  0.188695 -0.758872 -0.933237  0.955057     AM
4     E  0.190794  1.978757  2.605967  0.683509     SC

adiciona a coluna ao estado

In [51]:
df.set_index('Estado', inplace=True) #estado novo index

In [52]:
df

       index         W         X         Y         Z
Estado
RS         A  2.706850  0.628133  0.907969  0.503826
RJ         B  0.651118 -0.319318 -0.848077  0.605965
SP         C -2.018168  0.740122  0.528813 -0.589001
AM         D  0.188695 -0.758872 -0.933237  0.955057
SC         E  0.190794  1.978757  2.605967  0.683509

Indicies Multiniveis

In [53]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [54]:
outside #nivel 1

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [55]:
inside #nivel 2

[1, 2, 3, 1, 2, 3]

In [56]:
hier_index = list(zip(outside,inside)) #juntando as listas

In [57]:
hier_index #cria index multinivel

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [58]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [59]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [60]:
df = pd.DataFrame(np.random.randn(6, 2), index=hier_index, columns=['A', 'B']) #indices secundarios

In [61]:
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [62]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [63]:
df.index.names = ['Grupo', 'Numero'] #seleciona os dados no dataframe

In [64]:
df

                     A         B
Grupo Numero
G1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
G2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [65]:
df.xs ('G1') #seleciona só o g1, mais vantajoso usá-lo

               A         B
Numero
1       0.302665  1.693723
2      -1.706086 -1.159119
3      -0.134841  0.390528

In [66]:
df.xs(1, level='Numero')

              A         B
Grupo
G1     0.302665  1.693723
G2     0.166905  0.184502

In [67]:
d = {'A':[1, 2, np.nan], 'B':[5, np.nan, np.nan], 'C':[1, 2, 3]} #dicionario com mais valores que faltavam

Dados ausentes começa aqui em cima

In [68]:
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [69]:
df = pd.DataFrame(d)

In [70]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [71]:
df.dropna() #exclui apenas visivelmente

     A    B  C
0  1.0  5.0  1

In [72]:
df.dropna(thresh=2) #o resultado é excluir os valores faltantres

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [73]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [74]:
df.fillna(value='Fill na') #ele preenche os NaN com o que você quiser

         A        B  C
0      1.0      5.0  1
1      2.0  Fill na  2
2  Fill na  Fill na  3

In [75]:
df['A'].fillna(value=df['A'].mean()) #mais uma forma de tratamento

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [76]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [77]:
df.fillna(method='ffill')

/tmp/ipykernel_25610/1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

In [78]:
df.ffill() #essa resolve o anterior

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

GroupBy

In [79]:
data = {'Empresa':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Nome':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Venda':[200,120,340,124,243,350]} #dicionario

In [80]:
df = pd.DataFrame(data)

In [81]:
df

  Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [82]:

group = df.groupby('Empresa') #agrupa os dados

In [83]:
df

  Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [84]:
group

In [85]:
group.sum() #soma os vcalores do grupo

               Nome  Venda
Empresa
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [86]:
group.mean

In [87]:
group.describe()

        Venda
        count   mean         std    min     25%    50%     75%    max
Empresa
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [88]:
group.count()#contador

         Nome  Venda
Empresa
FB          2      2
GOOG        2      2
MSFT        2      2

Concatenar, Juntar e Mesclar

In [89]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])#data frames da aula

In [90]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) #data frames da aula

In [91]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])#data frames da aula - mesmo tamanho

In [92]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [93]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [94]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [95]:
pd.concat([df1,df2,df3]) #concatena as 3

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [96]:
pd.concat([df1,df2,df3],axis=1) #lado a lado

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [97]:
esquerda = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']}) #outros df
direita = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [98]:
esquerda

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [99]:
direita

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [100]:
pd.merge(esquerda,direita,how='inner',on='key') #mesclar os dois por causa da coluna key

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [101]:
esquerda = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
#aqui tem key 1 e 2
direita = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [102]:
pd.merge(esquerda, direita, on=['key1', 'key2']) #funciona como o merge do GIT, junta os dois

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [103]:
pd.merge(esquerda, direita, how='outer', on=['key1', 'key2']) #mantem os registros

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [104]:
pd.merge(esquerda, direita, how='right', on=['key1', 'key2'])#só da direita mantém

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [105]:
pd.merge(esquerda, direita, how='left', on=['key1', 'key2'])#apenas esquerda

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [106]:
esquerda = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2'])

direita = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [107]:
esquerda

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [108]:
direita

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [109]:
esquerda.join(direita) #join é método do df, coloca ordenado por indices iguais, da direita nessa caso

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [110]:
esquerda.join(direita, how='outer') #outer pega todos os indices

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

Operações com DF

In [111]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [112]:
df['col2'].unique() #procura dados e seleciona unicos dentro todos, ou seja, um 444 aparece, mesmo tendo 2. Poderia ter 10, ele retorna os valores sem repetição.

array([444, 555, 666])

In [113]:
np.unique(df['col2']) #semelhante

array([444, 555, 666])

In [114]:
len(np.unique(df['col2']))

3

In [115]:
df['col2'].nunique() #contagem

3

In [116]:
df['col2'].value_counts() #frequencia

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [117]:
df[(df['col1']>2) & (df['col2'] == 444)]

   col1  col2 col3
3     4   444  xyz

In [118]:
def vezes2(x):
    return x*2

In [119]:
df.sum()

col1              10
col2            2109
col3    abcdefghixyz
dtype: object

In [120]:
df['col1'].apply(vezes2) #aplicando a func genérica

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [121]:
df['col1'].apply(lambda x : x*x) #apply aplica para cada elemento

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [122]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [123]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [124]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [125]:
df.sort_values(by='col2', inplace = True) #ordena os dados pela coluna 2

In [126]:
df

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [127]:
df.isnull()

    col1   col2   col3
0  False  False  False
3  False  False  False
1  False  False  False
2  False  False  False

In [128]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [129]:
df['col1'].fillna(value=df['col1'].mean())

0    1.0
1    2.0
2    3.0
3    2.0
Name: col1, dtype: float64

In [130]:
df

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [131]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [132]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [133]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C']) #cria tabela "do excel - dinamica" usando D como valor

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

Entrada e saída de dados

In [135]:
df = pd.read_csv('/exemplo.txt', sep=';')

In [136]:
df

   Unnamed: 0   a   b   c   d
0           0   1   2   3   4
1           1   5   6   7   8
2           2   9  10  11  12
3           3  13  14  15  16

In [137]:
df= df + 1

In [138]:
df

   Unnamed: 0   a   b   c   d
0           1   2   3   4   5
1           2   6   7   8   9
2           3  10  11  12  13
3           4  14  15  16  17

In [139]:
df.to_csv('exemplo.csv', sep=';', decimal=',')

In [142]:
df = pd.read_excel('/Exemplo_Excel.xlsx', sheet_name='Sheet1')

In [143]:
df

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [144]:
df.to_excel('exemplo.xlsx', sheet_name='Sheet1') #salva o df em excel

In [145]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [146]:
type(df) #o arquivo de saida é uma lista

list

In [147]:
len(df) #tabelas

1

In [149]:
df[0] #assim como em um array, acessa a tabela

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
1,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
2,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
3,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
4,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
5,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
6,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
7,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
8,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
9,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
10,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
11,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
12,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
13,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
14,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
15,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
16,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
17,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
18,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
19,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
20,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
21,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
22,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
23,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
24,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527