In [1]:
# https://keithgalli.github.io/web-scraping/webpage.html link original

Load the webpage

In [5]:
from bs4 import BeautifulSoup as bs
import requests

# Load the webpage content
r = requests.get("https://keithgalli.github.io/web-scraping/webpage.html")

# Co vert to a beautiful soup Object
webpage = bs(r.content)

# Print out our html
print(webpage.prettify())

#aqui basicamente o que acontece é chamarmos a página, pegar o html e deixar legivel

<head>
 <title>
  Keith Galli's Page
 </title>
 <style>
  table {
    border-collapse: collapse;
  }
  th {
    padding:5px;
  }
  td {
    border: 1px solid #ddd;
    padding: 5px;
  }
  tr:nth-child(even) {
    background-color: #f2f2f2;
  }
  th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #add8e6;
    color: black;
  }
  .block {
  width: 100px;
  /*float: left;*/
    display: inline-block;
    zoom: 1;
  }
  .column {
  float: left;
  height: 200px;
  /*width: 33.33%;*/
  padding: 5px;
  }

  .row::after {
    content: "";
    clear: both;
    display: table;
  }
 </style>
</head>
<body>
 <h1>
  Welcome to my page!
 </h1>
 <img src="./images/selfie1.jpg" width="300px"/>
 <h2>
  About me
 </h2>
 <p>
  Hi, my name is Keith and I am a YouTuber who focuses on content related to programming, data science, and machine learning!
 </p>
 <p>
  Here is a link to my channel:
  <a href="https://www.youtube.com/kgmit">
   youtube.com/kgmit
  </a>
 </p>
 <p>
  I grew up in the great state of New Hampshire here in the USA. From an early age I always loved math. Around my senior year of high school, my brother first introduced me to programming. I found it a creative way to apply the same type of logical thinking skills that I enjoyed with math. This influenced me to study computer science in college and ultimately create a YouTube channel to share some things that I have learned along the way.
 </p>
 <h3>
  Hobbies
 </h3>
 <p>
  Believe it or not, I don't code 24/7. I love doing all sorts of active things. I like to play ice hockey &amp; table tennis as well as run, hike, skateboard, and snowboard. In addition to sports, I am a board game enthusiast. The two that I've been playing the most recently are
  <i>
   Settlers of Catan
  </i>
  and
  <i>
   Othello
  </i>
  .
 </p>
 <h3>
  Fun Facts
 </h3>
 <ul class="fun-facts">
  <li>
   Owned my dream car in high school
   <a href="#footer">
    <sup>
     1
    </sup>
   </a>
  </li>
  <li>
   Middle name is Ronald
  </li>
  <li>
   Never had been on a plane until college
  </li>
  <li>
   Dunkin Donuts coffee is better than Starbucks
  </li>
  <li>
   A favorite book series of mine is
   <i>
    Ender's Game
   </i>
  </li>
  <li>
   Current video game of choice is
   <i>
    Rocket League
   </i>
  </li>
  <li>
   The band that I've seen the most times live is the
   <i>
    Zac Brown Band
   </i>
  </li>
 </ul>
 <h2>
  Social Media
 </h2>
 I encourage you to check out my content on all social media platforms
 <br/>
 <ul class="socials">
  <li class="social instagram">
   <b>
    Instagram:
   </b>
   <a href="https://www.instagram.com/keithgalli/">
    https://www.instagram.com/keithgalli/
   </a>
  </li>
  <li class="social twitter">
   <b>
    Twitter:
   </b>
   <a href="https://twitter.com/keithgalli">
    https://twitter.com/keithgalli
   </a>
  </li>
  <li class="social linkedin">
   <b>
    LinkedIn:
   </b>
   <a href="https://www.linkedin.com/in/keithgalli/">
    https://www.linkedin.com/in/keithgalli/
   </a>
  </li>
  <li class="social tiktok">
   <b>
    TikTok:
   </b>
   <a href="https://www.tiktok.com/@keithgalli">
    https://www.tiktok.com/@keithgalli
   </a>
  </li>
 </ul>
 <h2>
  Photos
 </h2>
 Here are a few photos from a trip to italy I took last year
 <div class="row">
  <div class="column">
   <img alt="Lake Como" src="images/italy/lake_como.jpg" style="height:100%"/>
  </div>
  <div class="column">
   <img alt="Pontevecchio, Florence" src="images/italy/pontevecchio.jpg" style="height:100%"/>
  </div>
  <div class="column">
   <img alt="Riomaggiore, Cinque de Terre" src="images/italy/riomaggiore.jpg" style="height:100%"/>
  </div>
 </div>
 <div>
 </div>
 <h2>
  Table
 </h2>
 My MIT hockey stats :)
 <br/>
 <table class="hockey-stats">
  <thead>
   <tr>
    <th class="season" data-sort="">
     S
    </th>
    <th class="team" data-sort="team">
     Team
    </th>
    <th class="league" data-sort="league">
     League
    </th>
    <th class="regular gp" data-sort="gp">
     GP
    </th>
    <th class="regular g" data-sort="g">
     G
    </th>
    <th class="regular a" data-sort="a">
     A
    </th>
    <th class="regular tp" data-sort="tp">
     TP
    </th>
    <th class="regular pim" data-sort="pim">
     PIM
    </th>
    <th class="regular pm" data-sort="pm">
     +/-
    </th>
    <th class="separator">
    </th>
    <th class="postseason">
     POST
    </th>
    <th class="postseason gp" data-sort="playoffs-gp">
     GP
    </th>
    <th class="postseason g" data-sort="playoffs-g">
     G
    </th>
    <th class="postseason a" data-sort="playoffs-a">
     A
    </th>
    <th class="postseason tp" data-sort="playoffs-tp">
     TP
    </th>
    <th class="postseason pim" data-sort="playoffs-pim">
     PIM
    </th>
    <th class="postseason pm" data-sort="playoffs-pm">
     +/-
    </th>
   </tr>
  </thead>
  <tbody>
   <tr class="team-continent-NA">
    <td class="season sorted">
     2014-15
    </td>
    <td class="team">
     <i>
      <img src="images/flag.png"/>
     </i>
     <span class="txt-blue">
      <a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2014-2015?tab=stats">
       MIT (Mass. Inst. of Tech.)
      </a>
     </span>
    </td>
    <td class="league">
     <a href="https://www.eliteprospects.com/league/acha-ii/stats/2014-2015">
      ACHA II
     </a>
    </td>
    <td class="regular gp">
     17
    </td>
    <td class="regular g">
     3
    </td>
    <td class="regular a">
     9
    </td>
    <td class="regular tp">
     12
    </td>
    <td class="regular pim">
     20
    </td>
    <td class="regular pm">
    </td>
    <td class="separator">
     |
    </td>
    <td class="postseason">
     <a href="https://www.eliteprospects.com/league/acha-ii/stats/2014-2015">
     </a>
    </td>
    <td class="postseason gp">
    </td>
    <td class="postseason g">
    </td>
    <td class="postseason a">
    </td>
    <td class="postseason tp">
    </td>
    <td class="postseason pim">
    </td>
    <td class="postseason pm">
    </td>
   </tr>
   <tr class="team-continent-NA">
    <td class="season sorted">
     2015-16
    </td>
    <td class="team">
     <i>
      <img src="images/flag.png"/>
     </i>
     <span class="txt-blue">
      <a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2015-2016?tab=stats">
       MIT (Mass. Inst. of Tech.)
      </a>
     </span>
    </td>
    <td class="league">
     <a href="https://www.eliteprospects.com/league/acha-ii/stats/2015-2016">
      ACHA II
     </a>
    </td>
    <td class="regular gp">
     9
    </td>
    <td class="regular g">
     1
    </td>
    <td class="regular a">
     1
    </td>
    <td class="regular tp">
     2
    </td>
    <td class="regular pim">
     2
    </td>
    <td class="regular pm">
    </td>
    <td class="separator">
     |
    </td>
    <td class="postseason">
     <a href="https://www.eliteprospects.com/league/acha-ii/stats/2015-2016">
     </a>
    </td>
    <td class="postseason gp">
    </td>
    <td class="postseason g">
    </td>
    <td class="postseason a">
    </td>
    <td class="postseason tp">
    </td>
    <td class="postseason pim">
    </td>
    <td class="postseason pm">
    </td>
   </tr>
   <tr class="team-continent-NA">
    <td class="season sorted">
     2016-17
    </td>
    <td class="team">
     <i>
      <img src="images/flag.png"/>
     </i>
     <span class="txt-blue">
      <a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2016-2017?tab=stats">
       MIT (Mass. Inst. of Tech.)
      </a>
     </span>
    </td>
    <td class="league">
     <a href="https://www.eliteprospects.com/league/acha-ii/stats/2016-2017">
      ACHA II
     </a>
    </td>
    <td class="regular gp">
     12
    </td>
    <td class="regular g">
     5
    </td>
    <td class="regular a">
     5
    </td>
    <td class="regular tp">
     10
    </td>
    <td class="regular pim">
     8
    </td>
    <td class="regular pm">
     0
    </td>
    <td class="separator">
     |
    </td>
    <td class="postseason">
    </td>
    <td class="postseason gp">
    </td>
    <td class="postseason g">
    </td>
    <td class="postseason a">
    </td>
    <td class="postseason tp">
    </td>
    <td class="postseason pim">
    </td>
    <td class="postseason pm">
    </td>
   </tr>
   <tr class="team-continent-EU">
    <td class="season sorted">
     2017-18
    </td>
    <td class="team">
     Did not play
    </td>
    <td class="league">
     <a href="https://www.eliteprospects.com/stats">
     </a>
    </td>
    <td class="regular gp">
    </td>
    <td class="regular g">
    </td>
    <td class="regular a">
    </td>
    <td class="regular tp">
    </td>
    <td class="regular pim">
    </td>
    <td class="regular pm">
    </td>
    <td class="separator">
     |
    </td>
    <td class="postseason">
     <a href="https://www.eliteprospects.com/stats">
     </a>
    </td>
    <td class="postseason gp">
    </td>
    <td class="postseason g">
    </td>
    <td class="postseason a">
    </td>
    <td class="postseason tp">
    </td>
    <td class="postseason pim">
    </td>
    <td class="postseason pm">
    </td>
   </tr>
   <tr class="team-continent-NA">
    <td class="season sorted">
     2018-19
    </td>
    <td class="team">
     <i>
      <img src="images/flag.png"/>
     </i>
     <span class="txt-blue">
      <a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2018-2019?tab=stats">
       MIT (Mass. Inst. of Tech.)
      </a>
     </span>
    </td>
    <td class="league">
     <a href="https://www.eliteprospects.com/league/acha-iii/stats/2018-2019">
      ACHA III
     </a>
    </td>
    <td class="regular gp">
     8
    </td>
    <td class="regular g">
     5
    </td>
    <td class="regular a">
     10
    </td>
    <td class="regular tp">
     15
    </td>
    <td class="regular pim">
     8
    </td>
    <td class="regular pm">
    </td>
    <td class="separator">
     |
    </td>
    <td class="postseason">
     <a href="https://www.eliteprospects.com/league/acha-iii/stats/2018-2019">
     </a>
    </td>
    <td class="postseason gp">
    </td>
    <td class="postseason g">
    </td>
    <td class="postseason a">
    </td>
    <td class="postseason tp">
    </td>
    <td class="postseason pim">
    </td>
    <td class="postseason pm">
    </td>
   </tr>
  </tbody>
 </table>
 <h2>
  Mystery Message Challenge!
 </h2>
 <p>
  If you scrape the links below grabbing the &lt;p&gt; tag with id="secret-word", you'll discover a secret message :)
 </p>
 <div width="50%">
  <div align="left" class="block">
   <ul>
    <li>
     <a href="challenge/file_1.html">
      File 1
     </a>
    </li>
    <li>
     <a href="challenge/file_2.html">
      File 2
     </a>
    </li>
    <li>
     <a href="challenge/file_3.html">
      File 3
     </a>
    </li>
    <li>
     <a href="challenge/file_4.html">
      File 4
     </a>
    </li>
    <li>
     <a href="challenge/file_5.html">
      File 5
     </a>
    </li>
   </ul>
  </div>
  <div align="center" class="block">
   <ul>
    <li>
     <a href="challenge/file_6.html">
      File 6
     </a>
    </li>
    <li>
     <a href="challenge/file_7.html">
      File 7
     </a>
    </li>
    <li>
     <a href="challenge/file_8.html">
      File 8
     </a>
    </li>
    <li>
     <a href="challenge/file_9.html">
      File 9
     </a>
    </li>
    <li>
     <a href="challenge/file_10.html">
      File 10
     </a>
    </li>
   </ul>
  </div>
 </div>
 <h2>
  Footnotes
 </h2>
 <p id="footer">
  1. This was actually a minivan that I named Debora. Maybe not my dream car, but I loved her nonetheless.
 </p>
</body>

## Grab all of the social links from the webpage

Do this in at least 3 different ways

In [10]:
links = webpage.select("a")
links #aqui chama tudo o que tem a tag <a>

[<a href="https://www.youtube.com/kgmit">youtube.com/kgmit</a>,
 <a href="#footer"><sup>1</sup></a>,
 <a href="https://www.instagram.com/keithgalli/">https://www.instagram.com/keithgalli/</a>,
 <a href="https://twitter.com/keithgalli">https://twitter.com/keithgalli</a>,
 <a href="https://www.linkedin.com/in/keithgalli/">https://www.linkedin.com/in/keithgalli/</a>,
 <a href="https://www.tiktok.com/@keithgalli">https://www.tiktok.com/@keithgalli</a>,
 <a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2014-2015?tab=stats"> MIT (Mass. Inst. of Tech.) </a>,
 <a href="https://www.eliteprospects.com/league/acha-ii/stats/2014-2015"> ACHA II </a>,
 <a href="https://www.eliteprospects.com/league/acha-ii/stats/2014-2015"> </a>,
 <a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2015-2016?tab=stats"> MIT (Mass. Inst. of Tech.) </a>,
 <a href="https://www.eliteprospects.com/league/acha-ii/stats/2015-2016"> ACHA II </a>,
 <a href="https://www.eliteprospects.com/league/acha-ii/stats/2015-2016"> </a>,
 <a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2016-2017?tab=stats"> MIT (Mass. Inst. of Tech.) </a>,
 <a href="https://www.eliteprospects.com/league/acha-ii/stats/2016-2017"> ACHA II </a>,
 <a href="https://www.eliteprospects.com/stats"> </a>,
 <a href="https://www.eliteprospects.com/stats"> </a>,
 <a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2018-2019?tab=stats"> MIT (Mass. Inst. of Tech.) </a>,
 <a href="https://www.eliteprospects.com/league/acha-iii/stats/2018-2019"> ACHA III </a>,
 <a href="https://www.eliteprospects.com/league/acha-iii/stats/2018-2019"> </a>,
 <a href="challenge/file_1.html">File 1</a>,
 <a href="challenge/file_2.html">File 2</a>,
 <a href="challenge/file_3.html">File 3</a>,
 <a href="challenge/file_4.html">File 4</a>,
 <a href="challenge/file_5.html">File 5</a>,
 <a href="challenge/file_6.html">File 6</a>,
 <a href="challenge/file_7.html">File 7</a>,
 <a href="challenge/file_8.html">File 8</a>,
 <a href="challenge/file_9.html">File 9</a>,
 <a href="challenge/file_10.html">File 10</a>]

In [11]:
links = webpage.select("ul.socials")
links #aqui só muda o que olhamos

[<ul class="socials">
 <li class="social instagram"><b>Instagram: </b><a href="https://www.instagram.com/keithgalli/">https://www.instagram.com/keithgalli/</a></li>
 <li class="social twitter"><b>Twitter: </b><a href="https://twitter.com/keithgalli">https://twitter.com/keithgalli</a></li>
 <li class="social linkedin"><b>LinkedIn: </b><a href="https://www.linkedin.com/in/keithgalli/">https://www.linkedin.com/in/keithgalli/</a></li>
 <li class="social tiktok"><b>TikTok: </b><a href="https://www.tiktok.com/@keithgalli">https://www.tiktok.com/@keithgalli</a></li>
 </ul>]

In [13]:
links = webpage.select("ul.socials a")
links #aqui chama tudo o que tem a tag <a> e organiza pra isso

[<a href="https://www.instagram.com/keithgalli/">https://www.instagram.com/keithgalli/</a>,
 <a href="https://twitter.com/keithgalli">https://twitter.com/keithgalli</a>,
 <a href="https://www.linkedin.com/in/keithgalli/">https://www.linkedin.com/in/keithgalli/</a>,
 <a href="https://www.tiktok.com/@keithgalli">https://www.tiktok.com/@keithgalli</a>]

In [15]:
links = webpage.select("ul.socials a")
actual_links = [link['href'] for link in links]
actual_links

['https://www.instagram.com/keithgalli/',
 'https://twitter.com/keithgalli',
 'https://www.linkedin.com/in/keithgalli/',
 'https://www.tiktok.com/@keithgalli']

In [16]:
links = webpage.find("a")
links

In [18]:
links = webpage.find("ul", attrs={"class": "socials"})
links #aqui é passado outros parametros como atributos, classe

<ul class="socials">
<li class="social instagram"><b>Instagram: </b><a href="https://www.instagram.com/keithgalli/">https://www.instagram.com/keithgalli/</a></li>
<li class="social twitter"><b>Twitter: </b><a href="https://twitter.com/keithgalli">https://twitter.com/keithgalli</a></li>
<li class="social linkedin"><b>LinkedIn: </b><a href="https://www.linkedin.com/in/keithgalli/">https://www.linkedin.com/in/keithgalli/</a></li>
<li class="social tiktok"><b>TikTok: </b><a href="https://www.tiktok.com/@keithgalli">https://www.tiktok.com/@keithgalli</a></li>
</ul>

In [19]:
links = webpage.find("ul", attrs={"class": "socials"})
links #aqui é passado outros parametros como atributos, classe, se torna uma unica tag

<ul class="socials">
<li class="social instagram"><b>Instagram: </b><a href="https://www.instagram.com/keithgalli/">https://www.instagram.com/keithgalli/</a></li>
<li class="social twitter"><b>Twitter: </b><a href="https://twitter.com/keithgalli">https://twitter.com/keithgalli</a></li>
<li class="social linkedin"><b>LinkedIn: </b><a href="https://www.linkedin.com/in/keithgalli/">https://www.linkedin.com/in/keithgalli/</a></li>
<li class="social tiktok"><b>TikTok: </b><a href="https://www.tiktok.com/@keithgalli">https://www.tiktok.com/@keithgalli</a></li>
</ul>

In [24]:
ulist = webpage.find("ul", attrs={"class": "socials"})
links = ulist.find_all("a")
actual_links = [link['href'] for link in links]
actual_links # actual_links torna apenas nessa lista

['https://www.instagram.com/keithgalli/',
 'https://twitter.com/keithgalli',
 'https://www.linkedin.com/in/keithgalli/',
 'https://www.tiktok.com/@keithgalli']

In [27]:
links = webpage.select("li.social a")
links

[<a href="https://www.instagram.com/keithgalli/">https://www.instagram.com/keithgalli/</a>,
 <a href="https://twitter.com/keithgalli">https://twitter.com/keithgalli</a>,
 <a href="https://www.linkedin.com/in/keithgalli/">https://www.linkedin.com/in/keithgalli/</a>,
 <a href="https://www.tiktok.com/@keithgalli">https://www.tiktok.com/@keithgalli</a>]

In [28]:
actual_links

['https://www.instagram.com/keithgalli/',
 'https://twitter.com/keithgalli',
 'https://www.linkedin.com/in/keithgalli/',
 'https://www.tiktok.com/@keithgalli']

## Scrape the table

In [31]:
import pandas as pd

table = webpage.select("table.hockey-stats")[0] #descrever o primeiro elemento
table

<table class="hockey-stats">
<thead>
<tr>
<th class="season" data-sort="">S</th>
<th class="team" data-sort="team">Team</th>
<th class="league" data-sort="league">League</th>
<th class="regular gp" data-sort="gp">GP</th>
<th class="regular g" data-sort="g">G</th>
<th class="regular a" data-sort="a">A</th>
<th class="regular tp" data-sort="tp">TP</th>
<th class="regular pim" data-sort="pim">PIM</th>
<th class="regular pm" data-sort="pm">+/-</th>
<th class="separator"> </th>
<th class="postseason">POST</th>
<th class="postseason gp" data-sort="playoffs-gp">GP</th>
<th class="postseason g" data-sort="playoffs-g">G</th>
<th class="postseason a" data-sort="playoffs-a">A</th>
<th class="postseason tp" data-sort="playoffs-tp">TP</th>
<th class="postseason pim" data-sort="playoffs-pim">PIM</th>
<th class="postseason pm" data-sort="playoffs-pm">+/-</th>
</tr>
</thead>
<tbody>
<tr class="team-continent-NA">
<td class="season sorted">
                  2014-15
              </td>
<td class="team">
<i><img src="images/flag.png"/></i>
<span class="txt-blue">
<a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2014-2015?tab=stats"> MIT (Mass. Inst. of Tech.) </a>
</span>
</td>
<td class="league"> <a href="https://www.eliteprospects.com/league/acha-ii/stats/2014-2015"> ACHA II </a> </td>
<td class="regular gp">17</td>
<td class="regular g">3</td>
<td class="regular a">9</td>
<td class="regular tp">12</td>
<td class="regular pim">20</td>
<td class="regular pm"></td>
<td class="separator"> | </td>
<td class="postseason">
<a href="https://www.eliteprospects.com/league/acha-ii/stats/2014-2015"> </a>
</td>
<td class="postseason gp">
</td>
<td class="postseason g">
</td>
<td class="postseason a">
</td>
<td class="postseason tp">
</td>
<td class="postseason pim">
</td>
<td class="postseason pm">
</td>
</tr>
<tr class="team-continent-NA">
<td class="season sorted">
                  2015-16
              </td>
<td class="team">
<i><img src="images/flag.png"/></i>
<span class="txt-blue">
<a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2015-2016?tab=stats"> MIT (Mass. Inst. of Tech.) </a>
</span>
</td>
<td class="league"> <a href="https://www.eliteprospects.com/league/acha-ii/stats/2015-2016"> ACHA II </a> </td>
<td class="regular gp">9</td>
<td class="regular g">1</td>
<td class="regular a">1</td>
<td class="regular tp">2</td>
<td class="regular pim">2</td>
<td class="regular pm"></td>
<td class="separator"> | </td>
<td class="postseason">
<a href="https://www.eliteprospects.com/league/acha-ii/stats/2015-2016"> </a>
</td>
<td class="postseason gp">
</td>
<td class="postseason g">
</td>
<td class="postseason a">
</td>
<td class="postseason tp">
</td>
<td class="postseason pim">
</td>
<td class="postseason pm">
</td>
</tr>
<tr class="team-continent-NA">
<td class="season sorted">
                  2016-17
              </td>
<td class="team">
<i><img src="images/flag.png"/></i>
<span class="txt-blue">
<a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2016-2017?tab=stats"> MIT (Mass. Inst. of Tech.) </a>
</span>
</td>
<td class="league"> <a href="https://www.eliteprospects.com/league/acha-ii/stats/2016-2017"> ACHA II </a> </td>
<td class="regular gp">12</td>
<td class="regular g">5</td>
<td class="regular a">5</td>
<td class="regular tp">10</td>
<td class="regular pim">8</td>
<td class="regular pm">0</td>
<td class="separator"> | </td>
<td class="postseason">
</td>
<td class="postseason gp">
</td>
<td class="postseason g">
</td>
<td class="postseason a">
</td>
<td class="postseason tp">
</td>
<td class="postseason pim">
</td>
<td class="postseason pm">
</td>
</tr>
<tr class="team-continent-EU">
<td class="season sorted">
                  2017-18
              </td>
<td class="team">
                  Did not play
              </td>
<td class="league"> <a href="https://www.eliteprospects.com/stats"> </a> </td>
<td class="regular gp"></td>
<td class="regular g"></td>
<td class="regular a"></td>
<td class="regular tp"></td>
<td class="regular pim"></td>
<td class="regular pm"></td>
<td class="separator"> | </td>
<td class="postseason">
<a href="https://www.eliteprospects.com/stats"> </a>
</td>
<td class="postseason gp">
</td>
<td class="postseason g">
</td>
<td class="postseason a">
</td>
<td class="postseason tp">
</td>
<td class="postseason pim">
</td>
<td class="postseason pm">
</td>
</tr>
<tr class="team-continent-NA">
<td class="season sorted">
                  2018-19
              </td>
<td class="team">
<i><img src="images/flag.png"/></i>
<span class="txt-blue">
<a href="https://www.eliteprospects.com/team/10263/mit-mass.-inst.-of-tech./2018-2019?tab=stats"> MIT (Mass. Inst. of Tech.) </a>
</span>
</td>
<td class="league"> <a href="https://www.eliteprospects.com/league/acha-iii/stats/2018-2019"> ACHA III </a> </td>
<td class="regular gp">8</td>
<td class="regular g">5</td>
<td class="regular a">10</td>
<td class="regular tp">15</td>
<td class="regular pim">8</td>
<td class="regular pm"></td>
<td class="separator"> | </td>
<td class="postseason">
<a href="https://www.eliteprospects.com/league/acha-iii/stats/2018-2019"> </a>
</td>
<td class="postseason gp">
</td>
<td class="postseason g">
</td>
<td class="postseason a">
</td>
<td class="postseason tp">
</td>
<td class="postseason pim">
</td>
<td class="postseason pm">
</td>
</tr>
</tbody>
</table>

In [33]:
#l = []
#for tr in table_rows:
   # td = tr.find_all("td")
  #  row = [tr.text for tr in td]
 #   l.append(row)
#pd.DataFrame()l, columns=["A", "B", ...]
#codigo original stack overflow

In [36]:
table = webpage.select("table.hockey-stats")[0] #descrever o primeiro elemento
columns = table.find("thead").find_all("th")
columns_names = [c.string for c in columns]
columns_names #funcionou, mas não está como se deseja ver as informações

['S',
 'Team',
 'League',
 'GP',
 'G',
 'A',
 'TP',
 'PIM',
 '+/-',
 '\xa0',
 'POST',
 'GP',
 'G',
 'A',
 'TP',
 'PIM',
 '+/-']

In [51]:
import pandas as pd
table = webpage.select("table.hockey-stats")[0]
columns = table.find("thead").find_all("th")
column_names = [c.string for c in columns]

table_rows = table.find("tbody").find_all("tr")
l = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [str(tr.string).strip() for tr in td]
    l.append(row)

print(l[0]) # com isso consegue deixar melhor. Basicamente o que faz é pegar o seletor CSS, a primeira coluna, extrai o nome dela e pega as linhas, onde se cria uma lista de listas

df = pd.DataFrame(l, columns=column_names)
df.loc[df['Team'] != "Did not play"]

['2014-15', 'None', 'None', '17', '3', '9', '12', '20', 'None', '|', 'None', '', '', '', '', '', '']

         S  Team League  GP  G   A  TP PIM   +/-     POST GP G A TP PIM +/-
0  2014-15  None   None  17  3   9  12  20  None  |  None
1  2015-16  None   None   9  1   1   2   2  None  |  None
2  2016-17  None   None  12  5   5  10   8     0  |
4  2018-19  None   None   8  5  10  15   8  None  |  None

In [53]:
import pandas as pd
table = webpage.select("table.hockey-stats")[0]
columns = table.find("thead").find_all("th")
column_names = [c.string for c in columns]

table_rows = table.find("tbody").find_all("tr")
l = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [str(tr.string).strip() for tr in td]
    l.append(row)

print(l[0])
#aqui ele vai formatando de varias maneiras, até agradar kkkk
df = pd.DataFrame(l, columns=column_names)
df['GP']

['2014-15', 'None', 'None', '17', '3', '9', '12', '20', 'None', '|', 'None', '', '', '', '', '', '']

     GP GP
0    17
1     9
2    12
3  None
4     8

In [54]:
import pandas as pd
table = webpage.select("table.hockey-stats")[0]
columns = table.find("thead").find_all("th")
column_names = [c.string for c in columns]

table_rows = table.find("tbody").find_all("tr")
l = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [str(tr.string).strip() for tr in td]
    l.append(row)

print(l[0]) # com isso consegue deixar melhor. Basicamente o que faz é pegar o seletor CSS, a primeira coluna, extrai o nome dela e pega as linhas, onde se cria uma lista de listas

df = pd.DataFrame(l, columns=column_names)
df.loc[df['Team'] != "Did not play"]

['2014-15', 'None', 'None', '17', '3', '9', '12', '20', 'None', '|', 'None', '', '', '', '', '', '']

         S  Team League  GP  G   A  TP PIM   +/-     POST GP G A TP PIM +/-
0  2014-15  None   None  17  3   9  12  20  None  |  None
1  2015-16  None   None   9  1   1   2   2  None  |  None
2  2016-17  None   None  12  5   5  10   8     0  |
4  2018-19  None   None   8  5  10  15   8  None  |  None

## Grab all fun facts that use word "is"

In [57]:
facts = webpage.select("ul.fun-facts")
facts #todos os fatos engraçados

[<ul class="fun-facts">
 <li>Owned my dream car in high school <a href="#footer"><sup>1</sup></a></li>
 <li>Middle name is Ronald</li>
 <li>Never had been on a plane until college</li>
 <li>Dunkin Donuts coffee is better than Starbucks</li>
 <li>A favorite book series of mine is <i>Ender's Game</i></li>
 <li>Current video game of choice is <i>Rocket League</i></li>
 <li>The band that I've seen the most times live is the <i>Zac Brown Band</i></li>
 </ul>]

In [62]:
import re
#pegou as strings, mas ainda tem o none atrapahando
facts = webpage.select("ul.fun-facts li")
facts_with_is = [fact.find(string=re.compile("is")) for fact in facts]
facts_with_is

[None,
 'Middle name is Ronald',
 None,
 'Dunkin Donuts coffee is better than Starbucks',
 'A favorite book series of mine is ',
 'Current video game of choice is ',
 "The band that I've seen the most times live is the "]

In [66]:
import re

facts = webpage.select("ul.fun-facts li")
facts_with_is = [fact.find(string=re.compile("is")) for fact in facts]
facts_with_is = [fact for fact in facts_with_is if fact]
facts_with_is # com esse for, ele conseguiu se livrar dos none, isso porque só pega os fatos agora. A visualização ainda precisa melhorar.

['Middle name is Ronald',
 'Dunkin Donuts coffee is better than Starbucks',
 'A favorite book series of mine is ',
 'Current video game of choice is ',
 "The band that I've seen the most times live is the "]

In [68]:
import re

facts = webpage.select("ul.fun-facts li")
facts_with_is = [fact.find(string=re.compile("is")) for fact in facts]
facts_with_is = [fact.find_parent().get_text() for fact in facts_with_is if fact]
facts_with_is #pegou apenas o texto com o find parente e get text

['Middle name is Ronald',
 'Dunkin Donuts coffee is better than Starbucks',
 "A favorite book series of mine is Ender's Game",
 'Current video game of choice is Rocket League',
 "The band that I've seen the most times live is the Zac Brown Band"]

Download an Image

In [70]:
webpage.select("div.row div.column img") #aqui acha todas no site dele

[<img alt="Lake Como" src="images/italy/lake_como.jpg" style="height:100%"/>,
 <img alt="Pontevecchio, Florence" src="images/italy/pontevecchio.jpg" style="height:100%"/>,
 <img alt="Riomaggiore, Cinque de Terre" src="images/italy/riomaggiore.jpg" style="height:100%"/>]

In [73]:
images = webpage.select("div.row div.column img")
image_url = images[0]['src']
image_url #aqui mostra apenas depois do dominio, mas precimos para baixar a url completa

'images/italy/lake_como.jpg'

In [79]:
url = "https://keithgalli.github.io/web-scraping/"
r = requests.get(url+"webpage.html")

images = webpage.select("div.row div.column img")
image_url = images[0]['src']
full_url = url + image_url

img_data = requests.get(full_url).content
with open('lake_como.jpg', 'wb') as handler:
    handler.write(img_data) #aqui é claramente visivel o como funciona. Pega o site, destrincha as imagens, selecionaa imagem desejada[0], abre e baixa.

Solve the mistery challenge (desafio de achar a palavra secreta)

In [80]:
files = webpage.select("div.block a")
files

[<a href="challenge/file_1.html">File 1</a>,
 <a href="challenge/file_2.html">File 2</a>,
 <a href="challenge/file_3.html">File 3</a>,
 <a href="challenge/file_4.html">File 4</a>,
 <a href="challenge/file_5.html">File 5</a>,
 <a href="challenge/file_6.html">File 6</a>,
 <a href="challenge/file_7.html">File 7</a>,
 <a href="challenge/file_8.html">File 8</a>,
 <a href="challenge/file_9.html">File 9</a>,
 <a href="challenge/file_10.html">File 10</a>]

In [82]:
files = webpage.select("div.block a")
relative_files = [file['href'] for file in files]
relative_files # camimnhos relativos, importantes.

['challenge/file_1.html',
 'challenge/file_2.html',
 'challenge/file_3.html',
 'challenge/file_4.html',
 'challenge/file_5.html',
 'challenge/file_6.html',
 'challenge/file_7.html',
 'challenge/file_8.html',
 'challenge/file_9.html',
 'challenge/file_10.html']

In [84]:
files = webpage.select("div.block a")
relative_files = [file['href'] for file in files]

url = "https://keithgalli.github.io/web-scraping/"
for f in relative_files:
    full_url = url + f
    page = requests.get(full_url)
    bs_page = bs(page.content)
    print(bs_page.body.prettify())
    break

    #esse vai servir pra printar o body da pag visitada

<body>
 <p id="sccret-word">
  inscription
 </p>
 <p id="sccret-word">
  Ampex
 </p>
 <p id="sccret-word">
  bumblebee
 </p>
 <p id="sccret-word">
  nettle
 </p>
 <p id="sccret-word">
  helix
 </p>
 <p id="sccret-word">
  administrable
 </p>
 <p id="sccret-word">
  edict
 </p>
 <p id="sccret-word">
  Greenbelt
 </p>
 <p id="sccret-word">
  ibis
 </p>
 <p id="sccret-word">
  sinkhole
 </p>
 <p id="sccret-word">
  sonar
 </p>
 <p id="sccret-word">
  seminary
 </p>
 <p id="sccret-word">
  econometric
 </p>
 <p id="sccret-word">
  stampede
 </p>
 <p id="sccret-word">
  illegitimacy
 </p>
 <p id="sccret-word">
  Andorra
 </p>
 <p id="sccret-word">
  sworn
 </p>
 <p id="sccret-word">
  flatland
 </p>
 <p id="sccret-word">
  marksman
 </p>
 <p id="sccret-word">
  droopy
 </p>
 <p id="sccret-word">
  oven
 </p>
 <p id="sccret-word">
  Raleigh
 </p>
 <p id="sccret-word">
  breakwater
 </p>
 <p id="sccret-word">
  nutrition
 </p>
 <p id="sccret-word">
  Allan
 </p>
 <p id="sccret-word">
  antic
 </p>
 <p id="sccret-word">
  Montenegrin
 </p>
 <p id="sccret-word">
  penna
 </p>
 <p id="sccret-word">
  cereus
 </p>
 <p id="sccret-word">
  closure
 </p>
 <p id="sccret-word">
  tripe
 </p>
 <p id="sccret-word">
  cantilever
 </p>
 <p id="sccret-word">
  seashore
 </p>
 <p id="sccret-word">
  truth
 </p>
 <p id="sccret-word">
  bilharziasis
 </p>
 <p id="sccret-word">
  leadsman
 </p>
 <p id="sccret-word">
  pinnate
 </p>
 <p id="sccret-word">
  rho
 </p>
 <p id="sccret-word">
  oddball
 </p>
 <p id="sccret-word">
  prescriptive
 </p>
 <p id="sccret-word">
  attic
 </p>
 <p id="sccret-word">
  bedimmed
 </p>
 <p id="sccret-word">
  botany
 </p>
 <p id="sccret-word">
  trivia
 </p>
 <p id="sccret-word">
  pluggable
 </p>
 <p id="sccret-word">
  Carey
 </p>
 <p id="sccret-word">
  welfare
 </p>
 <p id="sccret-word">
  spectroscopy
 </p>
 <p id="sccret-word">
  epiphysis
 </p>
 <p id="sccret-word">
  pa
 </p>
 <p id="sccret-word">
  withdrawal
 </p>
 <p id="sccret-word">
  ugly
 </p>
 <p id="sccret-word">
  hillbilly
 </p>
 <p id="sccret-word">
  Sydney
 </p>
 <p id="sccret-word">
  Blinn
 </p>
 <p id="sccret-word">
  turpitude
 </p>
 <p id="sccret-word">
  Lenore
 </p>
 <p id="sccret-word">
  technetium
 </p>
 <p id="sccret-word">
  tableaux
 </p>
 <p id="sccret-word">
  bode
 </p>
 <p id="sccret-word">
  glycerin
 </p>
 <p id="sccret-word">
  chelate
 </p>
 <p id="sccret-word">
  sir
 </p>
 <p id="sccret-word">
  signify
 </p>
 <p id="sccret-word">
  crayfish
 </p>
 <p id="sccret-word">
  tsunami
 </p>
 <p id="sccret-word">
  armament
 </p>
 <p id="sccret-word">
  Paulson
 </p>
 <p id="sccret-word">
  Moran
 </p>
 <p id="sccret-word">
  Dunlop
 </p>
 <p id="sccret-word">
  irresolvable
 </p>
 <p id="sccret-word">
  fogy
 </p>
 <p id="sccret-word">
  heifer
 </p>
 <p id="sccret-word">
  genitive
 </p>
 <p id="sccret-word">
  edifice
 </p>
 <p id="sccret-word">
  Camelot
 </p>
 <p id="sccret-word">
  oppressor
 </p>
 <p id="sccret-word">
  kingfisher
 </p>
 <p id="sccret-word">
  foray
 </p>
 <p id="sccret-word">
  wonderful
 </p>
 <p id="sccret-word">
  slake
 </p>
 <p id="sccret-word">
  Hubbell
 </p>
 <p id="sccret-word">
  representative
 </p>
 <p id="sccret-word">
  excruciate
 </p>
 <p id="sccret-word">
  brockle
 </p>
 <p id="sccret-word">
  funeral
 </p>
 <p id="sccret-word">
  sentinel
 </p>
 <p id="sccret-word">
  synapse
 </p>
 <p id="sccret-word">
  harass
 </p>
 <p id="sccret-word">
  theta
 </p>
 <p id="sccret-word">
  portage
 </p>
 <p id="sccret-word">
  conform
 </p>
 <p id="sccret-word">
  wherein
 </p>
 <p id="sccret-word">
  hoc
 </p>
 <p id="sccret-word">
  chatty
 </p>
 <p id="sccret-word">
  ontogeny
 </p>
 <p id="sccret-word">
  birthrate
 </p>
 <p id="sccret-word">
  lawbreaking
 </p>
 <p id="sccret-word">
  Brice
 </p>
 <p id="sccret-word">
  maidenhair
 </p>
 <p id="sccret-word">
  alpaca
 </p>
 <p id="sccret-word">
  implore
 </p>
 <p id="sccret-word">
  sleet
 </p>
 <p id="sccret-word">
  briny
 </p>
 <p id="sccret-word">
  minnow
 </p>
 <p id="sccret-word">
  Zan
 </p>
 <p id="sccret-word">
  presumptive
 </p>
 <p id="sccret-word">
  mow
 </p>
 <p id="sccret-word">
  supremum
 </p>
 <p id="sccret-word">
  debacle
 </p>
 <p id="sccret-word">
  carbide
 </p>
 <p id="sccret-word">
  tenable
 </p>
 <p id="sccret-word">
  quotient
 </p>
 <p id="sccret-word">
  dilatory
 </p>
 <p id="sccret-word">
  pendulous
 </p>
 <p id="sccret-word">
  ovate
 </p>
 <p id="sccret-word">
  reverent
 </p>
 <p id="sccret-word">
  bassoon
 </p>
 <p id="sccret-word">
  presentation
 </p>
 <p id="sccret-word">
  seersucker
 </p>
 <p id="sccret-word">
  snakeroot
 </p>
 <p id="sccret-word">
  rankle
 </p>
 <p id="sccret-word">
  Kathy
 </p>
 <p id="sccret-word">
  climb
 </p>
 <p id="sccret-word">
  Fanny
 </p>
 <p id="sccret-word">
  intuitive
 </p>
 <p id="sccret-word">
  coconut
 </p>
 <p id="sccret-word">
  Laramie
 </p>
 <p id="sccret-word">
  maintain
 </p>
 <p id="sccret-word">
  ponderosa
 </p>
 <p id="sccret-word">
  suggest
 </p>
 <p id="sccret-word">
  deficit
 </p>
 <p id="sccret-word">
  homeward
 </p>
 <p id="sccret-word">
  farcical
 </p>
 <p id="sccret-word">
  perspicacity
 </p>
 <p id="sccret-word">
  glade
 </p>
 <p id="sccret-word">
  epithelium
 </p>
 <p id="sccret-word">
  multitude
 </p>
 <p id="sccret-word">
  piano
 </p>
 <p id="sccret-word">
  pathos
 </p>
 <p id="sccret-word">
  Tass
 </p>
 <p id="sccret-word">
  monomial
 </p>
 <p id="sccret-word">
  acidulous
 </p>
 <p id="sccret-word">
  upwell
 </p>
 <p id="sccret-word">
  fragile
 </p>
 <p id="sccret-word">
  Cruz
 </p>
 <p id="sccret-word">
  sniff
 </p>
 <p id="sccret-word">
  quill
 </p>
 <p id="sccret-word">
  mock
 </p>
 <p id="sccret-word">
  erratic
 </p>
 <p id="sccret-word">
  demitted
 </p>
 <p id="sccret-word">
  amuse
 </p>
 <p id="sccret-word">
  monochromator
 </p>
 <p id="sccret-word">
  A&amp;P
 </p>
 <p id="sccret-word">
  damselfly
 </p>
 <p id="sccret-word">
  commission
 </p>
 <p id="sccret-word">
  c's
 </p>
 <p id="sccret-word">
  plowmen
 </p>
 <p id="sccret-word">
  slanderous
 </p>
 <p id="sccret-word">
  logarithmic
 </p>
 <p id="sccret-word">
  elution
 </p>
 <p id="sccret-word">
  concentric
 </p>
 <p id="sccret-word">
  Youngstown
 </p>
 <p id="sccret-word">
  wrasse
 </p>
 <p id="sccret-word">
  Walter
 </p>
 <p id="sccret-word">
  monologue
 </p>
 <p id="sccret-word">
  doorknob
 </p>
 <p id="sccret-word">
  lockup
 </p>
 <p id="sccret-word">
  orthodontist
 </p>
 <p id="sccret-word">
  Greenbriar
 </p>
 <p id="sccret-word">
  frivolous
 </p>
 <p id="sccret-word">
  whiten
 </p>
 <p id="sccret-word">
  Gregory
 </p>
 <p id="sccret-word">
  lactate
 </p>
 <p id="sccret-word">
  derive
 </p>
 <p id="sccret-word">
  deprecatory
 </p>
 <p id="sccret-word">
  eosine
 </p>
 <p id="sccret-word">
  sommelier
 </p>
 <p id="sccret-word">
  bump
 </p>
 <p id="sccret-word">
  pyrimidine
 </p>
 <p id="sccret-word">
  aphasia
 </p>
 <p id="sccret-word">
  foray
 </p>
 <p id="sccret-word">
  fanfold
 </p>
 <p id="sccret-word">
  conducive
 </p>
 <p id="sccret-word">
  Langley
 </p>
 <p id="sccret-word">
  nominee
 </p>
 <p id="sccret-word">
  ruthless
 </p>
 <p id="sccret-word">
  northeast
 </p>
 <p id="sccret-word">
  poach
 </p>
 <p id="sccret-word">
  cot
 </p>
 <p id="sccret-word">
  whoopee
 </p>
 <p id="sccret-word">
  Holmdel
 </p>
 <p id="sccret-word">
  escort
 </p>
 <p id="sccret-word">
  platonic
 </p>
 <p id="sccret-word">
  meaty
 </p>
 <p id="sccret-word">
  apex
 </p>
 <p id="sccret-word">
  Doyle
 </p>
 <p id="sccret-word">
  Gould
 </p>
 <p id="sccret-word">
  mescaline
 </p>
 <p id="sccret-word">
  band
 </p>
 <p id="sccret-word">
  roster
 </p>
 <p id="sccret-word">
  Ponchartrain
 </p>
 <p id="sccret-word">
  alfonso
 </p>
 <p id="sccret-word">
  lumen
 </p>
 <p id="sccret-word">
  duplex
 </p>
 <p id="sccret-word">
  turbine
 </p>
 <p id="sccret-word">
  admiralty
 </p>
 <p id="sccret-word">
  cache
 </p>
 <p id="sccret-word">
  broccoli
 </p>
 <p id="sccret-word">
  wineskin
 </p>
 <p id="sccret-word">
  McCormick
 </p>
 <p id="sccret-word">
  Moen
 </p>
 <p id="sccret-word">
  Hastings
 </p>
 <p id="sccret-word">
  compulsion
 </p>
 <p id="sccret-word">
  Posner
 </p>
 <p id="sccret-word">
  survivor
 </p>
 <p id="sccret-word">
  subservient
 </p>
 <p id="sccret-word">
  Wehr
 </p>
 <p id="sccret-word">
  Robert
 </p>
 <p id="sccret-word">
  Sahara
 </p>
 <p id="sccret-word">
  McKinley
 </p>
 <p id="sccret-word">
  Daly
 </p>
 <p id="sccret-word">
  mindful
 </p>
 <p id="sccret-word">
  awn
 </p>
 <p id="sccret-word">
  jejunum
 </p>
 <p id="sccret-word">
  codicil
 </p>
 <p id="sccret-word">
  delectate
 </p>
 <p id="sccret-word">
  cargo
 </p>
 <p id="sccret-word">
  Mbabane
 </p>
 <p id="sccret-word">
  glottal
 </p>
 <p id="sccret-word">
  skull
 </p>
 <p id="sccret-word">
  toward
 </p>
 <p id="sccret-word">
  bleed
 </p>
 <p id="sccret-word">
  gingham
 </p>
 <p id="sccret-word">
  bright
 </p>
 <p id="sccret-word">
  vertical
 </p>
 <p id="sccret-word">
  descend
 </p>
 <p id="sccret-word">
  grate
 </p>
 <p id="sccret-word">
  mucus
 </p>
 <p id="sccret-word">
  Pentateuch
 </p>
 <p id="sccret-word">
  posy
 </p>
 <p id="sccret-word">
  Horus
 </p>
 <p id="sccret-word">
  forklift
 </p>
 <p id="sccret-word">
  eft
 </p>
 <p id="sccret-word">
  cleft
 </p>
 <p id="sccret-word">
  Leeds
 </p>
 <p id="sccret-word">
  watchband
 </p>
 <p id="sccret-word">
  rocket
 </p>
 <p id="sccret-word">
  group
 </p>
 <p id="sccret-word">
  embarcadero
 </p>
 <p id="sccret-word">
  Khrushchev
 </p>
 <p id="sccret-word">
  covary
 </p>
 <p id="sccret-word">
  roadhouse
 </p>
 <p id="sccret-word">
  dauphine
 </p>
 <p id="sccret-word">
  shame
 </p>
 <p id="sccret-word">
  impiety
 </p>
 <p id="sccret-word">
  virtue
 </p>
 <p id="sccret-word">
  grill
 </p>
 <p id="sccret-word">
  laboratory
 </p>
 <p id="sccret-word">
  paragon
 </p>
 <p id="sccret-word">
  prosecutor
 </p>
 <p id="sccret-word">
  penna
 </p>
 <p id="sccret-word">
  wheedle
 </p>
 <p id="sccret-word">
  screwball
 </p>
 <p id="sccret-word">
  midwives
 </p>
 <p id="sccret-word">
  roundhouse
 </p>
 <p id="sccret-word">
  apprentice
 </p>
 <p id="sccret-word">
  Jeremy
 </p>
 <p id="sccret-word">
  highwayman
 </p>
 <p id="sccret-word">
  afire
 </p>
 <p id="sccret-word">
  quizzed
 </p>
 <p id="sccret-word">
  Edgar
 </p>
 <p id="sccret-word">
  adject
 </p>
 <p id="sccret-word">
  fumigant
 </p>
 <p id="sccret-word">
  Congo
 </p>
 <p id="sccret-word">
  exterior
 </p>
 <p id="sccret-word">
  datum
 </p>
 <p id="sccret-word">
  injury
 </p>
 <p id="sccret-word">
  determinant
 </p>
 <p id="sccret-word">
  hansom
 </p>
 <p id="sccret-word">
  Flo
 </p>
 <p id="sccret-word">
  thrall
 </p>
 <p id="sccret-word">
  bayou
 </p>
 <p id="sccret-word">
  margarine
 </p>
 <p id="sccret-word">
  Schlitz
 </p>
 <p id="sccret-word">
  Mattson
 </p>
 <p id="sccret-word">
  wise
 </p>
 <p id="sccret-word">
  Patrice
 </p>
 <p id="sccret-word">
  colicky
 </p>
 <p id="sccret-word">
  concision
 </p>
 <p id="sccret-word">
  preachy
 </p>
 <p id="sccret-word">
  gymnasium
 </p>
 <p id="sccret-word">
  Battelle
 </p>
 <p id="sccret-word">
  ineligible
 </p>
 <p id="sccret-word">
  mart
 </p>
 <p id="sccret-word">
  Rydberg
 </p>
 <p id="sccret-word">
  dignity
 </p>
 <p id="sccret-word">
  extolling
 </p>
 <p id="sccret-word">
  consequential
 </p>
 <p id="sccret-word">
  prize
 </p>
 <p id="sccret-word">
  glare
 </p>
 <p id="sccret-word">
  marvelous
 </p>
 <p id="sccret-word">
  Yaounde
 </p>
 <p id="sccret-word">
  voice
 </p>
 <p id="sccret-word">
  muezzin
 </p>
 <p id="sccret-word">
  uranyl
 </p>
 <p id="sccret-word">
  intendant
 </p>
 <p id="sccret-word">
  bear
 </p>
 <p id="sccret-word">
  Blackwell
 </p>
 <p id="sccret-word">
  tomography
 </p>
 <p id="sccret-word">
  Pl
 </p>
 <p id="sccret-word">
  Gillespie
 </p>
 <p id="sccret-word">
  paternoster
 </p>
 <p id="sccret-word">
  minutemen
 </p>
 <p id="sccret-word">
  Argus
 </p>
 <p id="sccret-word">
  indigestible
 </p>
 <p id="sccret-word">
  hasten
 </p>
 <p id="sccret-word">
  patty
 </p>
 <p id="sccret-word">
  Thurman
 </p>
 <p id="sccret-word">
  almighty
 </p>
 <p id="sccret-word">
  Klux
 </p>
 <p id="sccret-word">
  McClain
 </p>
 <p id="sccret-word">
  sextuplet
 </p>
 <p id="sccret-word">
  illegal
 </p>
 <p id="sccret-word">
  histamine
 </p>
 <p id="sccret-word">
  Xavier
 </p>
 <p id="sccret-word">
  farewell
 </p>
 <p id="sccret-word">
  Durham
 </p>
 <p id="sccret-word">
  Hermosa
 </p>
 <p id="sccret-word">
  London
 </p>
 <p id="sccret-word">
  proponent
 </p>
 <p id="sccret-word">
  Oklahoma
 </p>
 <p id="sccret-word">
  evangelic
 </p>
 <p id="sccret-word">
  Imbrium
 </p>
 <p id="sccret-word">
  Heinz
 </p>
 <p id="sccret-word">
  nectar
 </p>
 <p id="sccret-word">
  hysteria
 </p>
 <p id="sccret-word">
  recrudescent
 </p>
 <p id="sccret-word">
  surtout
 </p>
 <p id="sccret-word">
  hole
 </p>
 <p id="sccret-word">
  conclusive
 </p>
 <p id="sccret-word">
  Smyrna
 </p>
 <p id="sccret-word">
  trashy
 </p>
 <p id="sccret-word">
  ample
 </p>
 <p id="sccret-word">
  priggish
 </p>
 <p id="sccret-word">
  Shakespearean
 </p>
 <p id="sccret-word">
  Brunswick
 </p>
 <p id="sccret-word">
  piss
 </p>
 <p id="sccret-word">
  nose
 </p>
 <p id="sccret-word">
  Lydia
 </p>
 <p id="sccret-word">
  millinery
 </p>
 <p id="sccret-word">
  millennium
 </p>
 <p id="sccret-word">
  attempt
 </p>
 <p id="sccret-word">
  qualm
 </p>
 <p id="sccret-word">
  Keaton
 </p>
 <p id="sccret-word">
  made
 </p>
 <p id="sccret-word">
  Nicaragua
 </p>
 <p id="sccret-word">
  printmake
 </p>
 <p id="sccret-word">
  drawn
 </p>
 <p id="sccret-word">
  induce
 </p>
 <p id="sccret-word">
  Antioch
 </p>
 <p id="sccret-word">
  bromide
 </p>
 <p id="sccret-word">
  mechanism
 </p>
 <p id="sccret-word">
  wingspan
 </p>
 <p id="sccret-word">
  immoderate
 </p>
 <p id="sccret-word">
  enamel
 </p>
 <p id="sccret-word">
  Sanskrit
 </p>
 <p id="sccret-word">
  skein
 </p>
 <p id="sccret-word">
  lure
 </p>
 <p id="sccret-word">
  zombie
 </p>
 <p id="sccret-word">
  magnesium
 </p>
 <p id="sccret-word">
  gulp
 </p>
 <p id="sccret-word">
  tote
 </p>
 <p id="sccret-word">
  obvious
 </p>
 <p id="sccret-word">
  growth
 </p>
 <p id="sccret-word">
  insofar
 </p>
 <p id="sccret-word">
  seismic
 </p>
 <p id="sccret-word">
  stereo
 </p>
 <p id="sccret-word">
  religiosity
 </p>
 <p id="sccret-word">
  microscopy
 </p>
 <p id="sccret-word">
  vivace
 </p>
 <p id="sccret-word">
  white
 </p>
 <p id="sccret-word">
  various
 </p>
 <p id="sccret-word">
  dunk
 </p>
 <p id="sccret-word">
  Solon
 </p>
 <p id="sccret-word">
  frivolity
 </p>
 <p id="sccret-word">
  whomever
 </p>
 <p id="sccret-word">
  ossify
 </p>
 <p id="sccret-word">
  Hathaway
 </p>
 <p id="sccret-word">
  bedlam
 </p>
 <p id="sccret-word">
  eclectic
 </p>
 <p id="sccret-word">
  whip
 </p>
 <p id="sccret-word">
  cheesemaking
 </p>
 <p id="sccret-word">
  pant
 </p>
 <p id="sccret-word">
  examination
 </p>
 <p id="sccret-word">
  Durkin
 </p>
 <p id="sccret-word">
  intestate
 </p>
 <p id="sccret-word">
  excisable
 </p>
 <p id="sccret-word">
  loathe
 </p>
 <p id="sccret-word">
  ineligible
 </p>
 <p id="sccret-word">
  idiomatic
 </p>
 <p id="sccret-word">
  Lowe
 </p>
 <p id="sccret-word">
  radiography
 </p>
 <p id="sccret-word">
  kit
 </p>
 <p id="sccret-word">
  subtrahend
 </p>
 <p id="sccret-word">
  honey
 </p>
 <p id="sccret-word">
  Ogden
 </p>
 <p id="sccret-word">
  bergamot
 </p>
 <p id="sccret-word">
  ambassador
 </p>
 <p id="sccret-word">
  Gilmore
 </p>
 <p id="sccret-word">
  ectopic
 </p>
 <p id="sccret-word">
  transferring
 </p>
 <p id="sccret-word">
  marinate
 </p>
 <p id="sccret-word">
  mouthpart
 </p>
 <p id="sccret-word">
  rheum
 </p>
 <p id="sccret-word">
  chevy
 </p>
 <p id="sccret-word">
  trial
 </p>
 <p id="sccret-word">
  Alicia
 </p>
 <p id="sccret-word">
  opalescent
 </p>
 <p id="sccret-word">
  vagina
 </p>
 <p id="sccret-word">
  fillet
 </p>
 <p id="sccret-word">
  succinct
 </p>
 <p id="sccret-word">
  alloy
 </p>
 <p id="sccret-word">
  avaricious
 </p>
 <p id="sccret-word">
  opium
 </p>
 <p id="sccret-word">
  devilish
 </p>
 <p id="sccret-word">
  bawl
 </p>
 <p id="sccret-word">
  cranberry
 </p>
 <p id="sccret-word">
  berne
 </p>
 <p id="sccret-word">
  cruel
 </p>
 <p id="sccret-word">
  mimosa
 </p>
 <p id="sccret-word">
  everyone
 </p>
 <p id="sccret-word">
  shrub
 </p>
 <p id="sccret-word">
  slough
 </p>
 <p id="sccret-word">
  peat
 </p>
 <p id="sccret-word">
  circumcision
 </p>
 <p id="sccret-word">
  praecox
 </p>
 <p id="sccret-word">
  digestive
 </p>
 <p id="sccret-word">
  complement
 </p>
 <p id="sccret-word">
  nucleus
 </p>
 <p id="sccret-word">
  Kennecott
 </p>
 <p id="sccret-word">
  grantor
 </p>
 <p id="sccret-word">
  direct
 </p>
 <p id="sccret-word">
  airdrop
 </p>
 <p id="sccret-word">
  juicy
 </p>
 <p id="sccret-word">
  fearful
 </p>
 <p id="sccret-word">
  hangover
 </p>
 <p id="sccret-word">
  clomp
 </p>
 <p id="sccret-word">
  manpower
 </p>
 <p id="sccret-word">
  mere
 </p>
 <p id="sccret-word">
  Sorensen
 </p>
 <p id="sccret-word">
  brevity
 </p>
 <p id="sccret-word">
  pick
 </p>
 <p id="sccret-word">
  haberdashery
 </p>
 <p id="sccret-word">
  soapy
 </p>
 <p id="sccret-word">
  Thomas
 </p>
 <p id="sccret-word">
  deteriorate
 </p>
 <p id="sccret-word">
  dam
 </p>
 <p id="sccret-word">
  exothermic
 </p>
 <p id="sccret-word">
  brush
 </p>
 <p id="sccret-word">
  astray
 </p>
 <p id="sccret-word">
  Rubin
 </p>
 <p id="sccret-word">
  Ghent
 </p>
 <p id="sccret-word">
  dull
 </p>
 <p id="sccret-word">
  shopworn
 </p>
 <p id="sccret-word">
  Crosby
 </p>
 <p id="sccret-word">
  adhesion
 </p>
 <p id="sccret-word">
  macintosh
 </p>
 <p id="sccret-word">
  compulsive
 </p>
 <p id="sccret-word">
  brig
 </p>
 <p id="sccret-word">
  Auberge
 </p>
 <p id="sccret-word">
  crucify
 </p>
 <p id="sccret-word">
  expressible
 </p>
 <p id="sccret-word">
  concept
 </p>
 <p id="sccret-word">
  jasper
 </p>
 <p id="sccret-word">
  police
 </p>
 <p id="sccret-word">
  Tyburn
 </p>
 <p id="sccret-word">
  figurate
 </p>
 <p id="sccret-word">
  slush
 </p>
 <p id="sccret-word">
  Maya
 </p>
 <p id="sccret-word">
  inhabit
 </p>
 <p id="sccret-word">
  agnostic
 </p>
 <p id="sccret-word">
  bland
 </p>
 <p id="sccret-word">
  Tito
 </p>
 <p id="sccret-word">
  contumacy
 </p>
 <p id="sccret-word">
  sedition
 </p>
 <p id="sccret-word">
  Denny
 </p>
 <p id="sccret-word">
  oxalate
 </p>
 <p id="sccret-word">
  postman
 </p>
 <p id="sccret-word">
  doormen
 </p>
 <p id="sccret-word">
  toil
 </p>
 <p id="sccret-word">
  Judith
 </p>
 <p id="sccret-word">
  backgammon
 </p>
 <p id="sccret-word">
  abnegation
 </p>
 <p id="sccret-word">
  provision
 </p>
 <p id="sccret-word">
  disciple
 </p>
 <p id="sccret-word">
  depository
 </p>
 <p id="sccret-word">
  stress
 </p>
 <p id="sccret-word">
  fallow
 </p>
 <p id="sccret-word">
  programmatic
 </p>
 <p id="sccret-word">
  brothel
 </p>
 <p id="sccret-word">
  absolve
 </p>
 <p id="sccret-word">
  imbalance
 </p>
 <p id="sccret-word">
  jet
 </p>
 <p id="sccret-word">
  streetcar
 </p>
 <p id="sccret-word">
  insert
 </p>
 <p id="sccret-word">
  wrath
 </p>
 <p id="sccret-word">
  everything
 </p>
 <p id="sccret-word">
  Caviness
 </p>
 <p id="sccret-word">
  gleam
 </p>
 <p id="sccret-word">
  Imbrium
 </p>
 <p id="sccret-word">
  missionary
 </p>
 <p id="sccret-word">
  ought
 </p>
 <p id="sccret-word">
  Romulus
 </p>
 <p id="sccret-word">
  sledge
 </p>
 <p id="sccret-word">
  tranquil
 </p>
 <p id="sccret-word">
  shuddery
 </p>
 <p id="sccret-word">
  sawmill
 </p>
 <p id="sccret-word">
  relaxation
 </p>
 <p id="sccret-word">
  Woodlawn
 </p>
 <p id="sccret-word">
  tabulate
 </p>
 <p id="sccret-word">
  ineluctable
 </p>
 <p id="sccret-word">
  agronomy
 </p>
 <p id="sccret-word">
  photo
 </p>

In [85]:
files = webpage.select("div.block a")
relative_files = [file['href'] for file in files]

url = "https://keithgalli.github.io/web-scraping/"
for f in relative_files:
    full_url = url + f
    page = requests.get(full_url)
    bs_page = bs(page.content)
    secret_word_element = bs_page.find("p", attrs={"id": "secret-word"})
    secret_word = secret_word_element.string
    print(secret_word) # a piada pronta, ter certeza de dar o like. Aqui aparece completo e a chave secreta finalmente é desvendada. O que acontece aqui é como um filtro

Make
sure
to
smash
that
like
button
and
subscribe
!!!